### This file acts as the global config across the website.
### Any variables in this file can be accessed in other files using
###    `{{ site.variable }}`


######################
# Site configuration #
######################
# This title will display across the website
title: "Mentor Matching Online"
# This description is predominantly for Search Engine Optimisation
description: "Mentoring, made easy. Use these guides, resources and tools to deliver a large scale, mentoring programme."
# Instead of "author", have the organisation name as the default
author: "John Peart, Jonathan Kerr"
organisation: "Mentor Matching Online"
email: "info@mentormatching.online"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mentormatching.online"

###################
# Header settings #
###################
header-menu--links--hidden: false


###################
# Footer settings #
###################
# This text will be displayed at the bottom of the website.
footer--production-notice: "Site created by <a href='https://www.johnpe.art/' class='link--inverse'>John Peart</a>."
#footer--copyright-notice: ""

##############
# Menu links #
##############
# Menu links
links:
  - display-text: "Home"
    alt-text: "Visit the home page"
    url: "/"
    header: true
    footer: false
    sidebar: false
  - display-text: "Matching software"
    alt-text: "Use the mentor matching software"
    url: "https://github.com/mentor-matching-online/mentor-match"
    header: false
    footer: true
    sidebar: true
  - display-text: "About"
    alt-text: "Find out more about this project"
    url: "/about"
    header: true
    footer: true
    sidebar: false

###############
# Asset paths #
###############
# General paths
css-path: "https://assets.mentormatching.online/styles/styles.css"
js-path: "https://assets.mentormatching.online/scripts/scripts.js"

# Favicons and social graph
social-media-image: "https://assets.mentormatching.online/images/site/social-media.png"
favicon: "https://assets.mentormatching.online/favicon.ico"
favicon-svg: "https://assets.mentormatching.online/images/site/favicon-pinned-svg.svg"
favicon-pinned-svg: "https://assets.mentormatching.online/images/site/favicon-pinned-svg.svg"
favicon-large-png: "https://assets.mentormatching.online/images/site/favicon-large-png.png"
theme-colour: "#373151"



##################################
# Analytics and domain ownership #
##################################
# Google settings
google-site-verification: ""

###############
# Collections #
###############
#This is the default permalink for the "_posts" folder.
permalink: /:year/:month/:day/:title:output_ext

collections:
  guides:    
    sort_by: order
    output: true
    permalink: /guide/:title/
    defaults:
      values:
        layout: guide
  software:    
    sort_by: order
    output: true
    permalink: /software/:title/
    defaults:
      values:
        layout: docs
  people:    
    output: false
                
##################
# Build settings #
##################
remote_theme: mentor-matching-online/jekyll-theme
permalink: pretty
markdown: kramdown
kramdown:
  toc_levels: "2"
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/